apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: corvus
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "corvus.example.com"
spec:
  tls:
    - hosts:
        - corvus.example.com
      secretName: corvus-tls
  rules:
    - host: corvus.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: corvus-app
                port:
                  name: http
