apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis-service.yaml
  - redis-statefulset.yaml
  - sentinel-service.yaml
  - sentinel-statefulset.yaml
  - failover-controller.yaml
  - configmap.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - podmonitor.yaml
