apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: corvus-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: corvus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/part-of: corvus
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - corvus
