apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretserver-app
spec:
  template:
    spec:
      imagePullSecrets:
        - name: quay-registry
      containers:
        - name: app
          imagePullPolicy: Always
