nameReference:
  - kind: ClusterIssuer
    group: cert-manager.io
    fieldSpecs:
      - kind: Certificate
        path: spec/issuerRef/name
        group: cert-manager.io
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: StatefulSet
        path: spec/template/spec/volumes/configMap/name
        group: apps
      - kind: Deployment
        path: spec/template/spec/volumes/configMap/name
        group: apps
