apiVersion: apps/v1
kind: Deployment
metadata:
  name: corvus-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: corvus-redis-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: redis://:$(REDIS_PASSWORD)@redis-master:6379/0
